version: "3.9"
services:
  service:
    build: ./TagsterWebAPI
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - tagter-web-api-configuration:/app/Configuration
  seq:
    image: datalust/seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - seq-data:/data
  db:
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - 15591:1433
      - 5022:5022
    volumes: 
      - db-backups:/var/opt/mssql/backups
      - db-sqlserver:/var/opt/sqlserver
      - db-mssql:/var/opt/mssql
  redis:
    image: redis:latest
    volumes: 
      - redis-data:/usr/local/etc/redis

volumes:
  tagter-web-api-configuration:
    external: true
  seq-data:
    external: true
  db-backups:
    external: true
  db-sqlserver:
    external: true
  db-mssql:
    external: true
  redis-data:
    external: true