version: "3.9"
services:
  service:
    container_name: tagster
    build: ./TagsterWebAPI
    restart: unless-stopped
    networks:
      - tagster
    ports:
      - 5000:9000
    volumes:
      - tagter-web-api-configuration:/app/Configuration
    depends_on:
      - seq
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 100m
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    networks:
      - tagster
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    volumes:
      - seq-data:/data
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 100m
  db:
    container_name: sql
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    networks:
      - tagster
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - 15591:1433
      - 5022:5022
    volumes:
      - db-backups:/var/opt/mssql/backups
      - db-sqlserver:/var/opt/sqlserver
      - db-mssql:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 2000m
        reservations:
          memory: 500m
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - tagster
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 100m

volumes:
  tagter-web-api-configuration:
    external: false
  seq-data:
    external: false
  db-backups:
    external: false
  db-sqlserver:
    external: false
  db-mssql:
    external: false
  redis-data:
    external: false

networks:
  tagster:
    name: tagster-network
