version: "3.9"
services:
  service:
    container_name: tagster
    build: ./TagsterWebAPI
    restart: unless-stopped
    networks:
      - tagster
    ports:
      - 5000:9000
    volumes:
      - tagter-web-api-configuration:/app/Configuration
    depends_on:
      - seq
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 100m
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    networks:
      - tagster
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    volumes:
      - seq-data:/data
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 100m
  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    networks:
      - tagster
    environment:
      - POSTGRES_PASSWORD=Your_password123
      - POSTGRES_USER=tagster
      - POSTGRES_DB=tagster
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2000m
        reservations:
          memory: 500m
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - tagster
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 100m
        reservations:
          memory: 50m

volumes:
  tagter-web-api-configuration:
    external: false
  seq-data:
    external: false
  redis-data:
    external: false
  db-data:
    external: false

networks:
  tagster:
    name: tagster-network
