// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tagster.DataAccess.DBContexts;

namespace Tagster.DataAccess.Migrations
{
    [DbContext(typeof(TagsterDbContext))]
<<<<<<< HEAD:TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210905081434_Initial.Designer.cs
    [Migration("20210905081434_Initial")]
=======
    [Migration("20210906183605_Initial")]
>>>>>>> e56f5e008b44f871bf3346eb31d0999174b491f7:TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210906183605_Initial.Designer.cs
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tagster.DataAccess.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

<<<<<<< HEAD:TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210905081434_Initial.Designer.cs
=======
            modelBuilder.Entity("Tagster.DataAccess.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

>>>>>>> e56f5e008b44f871bf3346eb31d0999174b491f7:TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210906183605_Initial.Designer.cs
            modelBuilder.Entity("Tagster.DataAccess.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Tagster.DataAccess.Entities.User", b =>
                {
<<<<<<< HEAD:TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210905081434_Initial.Designer.cs
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
=======
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
>>>>>>> e56f5e008b44f871bf3346eb31d0999174b491f7:TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210906183605_Initial.Designer.cs

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tagster.DataAccess.Entities.Tag", b =>
                {
                    b.HasOne("Tagster.DataAccess.Entities.Profile", null)
                        .WithMany("ProfileTags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tagster.DataAccess.Entities.Profile", b =>
                {
                    b.Navigation("ProfileTags");
                });
#pragma warning restore 612, 618
        }
    }
}
